version: "3.9"
services:
    php:
        container_name: 'php_container'
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - "8765:80"
        volumes:
            - ./:/var/www/html/
        environment:
            - XDEBUG_MODE=coverage
